//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class simpleBudget
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public simpleBudget()
    {
        this.simpleBudgetRules = new HashSet<simpleBudgetRule>();
        this.simpleBudgetExpecteds = new HashSet<simpleBudgetExpected>();
    }

    public int simpleBudgetId { get; set; }
    public string label1 { get; set; }
    public string label2 { get; set; }
    public string label3 { get; set; }
    public System.DateTime created_at { get; set; }
    public string created_by { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
    public string updated_by { get; set; }
    public Nullable<int> sortOrder { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<simpleBudgetRule> simpleBudgetRules { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<simpleBudgetExpected> simpleBudgetExpecteds { get; set; }
}

public partial class simpleBudgetCalculatedActual
{
    public int simpleBudgetActualId { get; set; }
    public Nullable<int> simpleBudgetExpectedId { get; set; }
    public decimal amount { get; set; }
    public Nullable<System.DateTime> calculated { get; set; }

    public virtual simpleBudgetExpected simpleBudgetExpected { get; set; }
}

public partial class simpleBudgetExpected
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public simpleBudgetExpected()
    {
        this.simpleBudgetCalculatedActuals = new HashSet<simpleBudgetCalculatedActual>();
    }

    public int simpleBudgetExpectedId { get; set; }
    public Nullable<int> simpleBudgetId { get; set; }
    public Nullable<decimal> amount { get; set; }
    public Nullable<System.DateTime> transactionStartDate { get; set; }
    public Nullable<System.DateTime> transactionEndDate { get; set; }
    public Nullable<System.DateTime> effectiveDate { get; set; }
    public Nullable<System.DateTime> retiredDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<simpleBudgetCalculatedActual> simpleBudgetCalculatedActuals { get; set; }
    public virtual simpleBudget simpleBudget { get; set; }
}

public partial class simpleBudgetRule
{
    public int simpleBudgetRuleId { get; set; }
    public int simpleBudgetId { get; set; }
    public int ruleIndex { get; set; }
    public int usePayee { get; set; }
    public int useCat { get; set; }
    public int useTag { get; set; }
    public string payeePattern { get; set; }
    public string categoryPattern { get; set; }
    public string tagpattern { get; set; }
    public System.DateTime effectiveDate { get; set; }
    public System.DateTime retiredDate { get; set; }
    public System.DateTime created_at { get; set; }
    public string created_by { get; set; }
    public Nullable<System.DateTime> updated_at { get; set; }
    public string updated_by { get; set; }

    public virtual simpleBudget simpleBudget { get; set; }
}
